### ISSUE TITLE
Switch to YAML file testing setup

### ISSUE THREAD

**Issue by ericnorris** [ericnorris/cryptopals-solutions#4]
Per #2, after investigating a couple options I feel that a YAML file test framework would be the cleanest and easiest solution.
## Project Layout

```
cryptopals/
    set1/
    set2/
    ...
test/
    conftest.py
    set1/
        challenge_01.yaml
        ...
    set2/
    ...
```
## Example YAML File

``` yaml

---
# Each YAML document represents a single parametrization
param_name : value
other_param: value

---
param_name : different_value
other_param: different_value
```
